[package]
name = "MintNFTExamplePart3"
version = "0.0.0"

[addresses]
mint_nft = "_"
# replace the admin_addr with the actual admin address we created using CLI
admin_addr = "_"

[dev-addresses]
mint_nft = "0xcafe"
admin_addr = "0xbeef"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework' }
AptosToken = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-token' }

[dev-dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
