[package]
name = "ResourceAccountExample"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
source_addr = "_"

[dev-addresses]
source_addr = "0xcafe"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework' }

[dev-dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
