[package]
name = "CommonAccount"
version = "1.0.0"

[addresses]
common_account = "_"

[dev-addresses]
common_account = "0xcafe"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework' }

[dev-dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
