# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.0.0'

[addresses]
upgrade_and_govern = '_'

[dev-addresses]
upgrade_and_govern = '0xcafe'

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework' }

[dev-dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
# <:!:manifest
