[package]
name = "CliArgs"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
test_account = "_"

[dev-addresses]
test_account = "0xcafe"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework' }

[dev-dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }