[package]
name = "PostMintExample"
version = "0.0.0"

[addresses]
post_mint_reveal_nft = "_"

[dev-addresses]
post_mint_reveal_nft = "0xcafe"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework' }
AptosToken = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-token' }

[dev-dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosToken = { local = "../../framework/aptos-token" }
