[package]
name = "IterableTable"
version = "0.0.1"

[addresses]
iterable_table_account = "_"

[dev-addresses]
iterable_table_account = "0xcafe"

[dependencies]
AptosStdlib = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-stdlib' }

[dev-dependencies]
AptosStdLib = { local = "../../framework/aptos-stdlib" }
